# Generated by Django 4.2.8 on 2023-12-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_inflation_percent_change_mom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inflation',
            old_name='percent_change_yom',
            new_name='percent_change_all',
        ),
    ]
