# Generated by Django 4.2.8 on 2024-01-07 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_percent_change_yom_inflation_percent_change_all'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
