# Generated by Django 4.2.8 on 2024-01-21 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='city',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='country',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='state',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ipaddress',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
